### ISSUE TITLE
Layer number selection UI doesn't show when using &tog / &to in macros

### ISSUE THREAD

**Issue by kadoyau** [KinesisCorporation/Adv360-Pro-GUI#12]
When I attempt to use &tog and &to in macros, I am having trouble being able to select the layer number for the jump destination. I believe the expected behavior is to be able to select the layer number, similar to how it is done in the Layers UI.

If I try to correct this problem outside of the GUI by directly modifying the source code, I can no longer edit within the GUI due to the existing issue #9.

[![Image from Gyazo](https://i.gyazo.com/00601151a1c061f27bc083d57666f112.gif)](https://gyazo.com/00601151a1c061f27bc083d57666f112)

When I open the console in the dev tool, I receive the following error:
```
TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.results (app.bundle.js:1:295337)
    at Cn.run (app.bundle.js:1:233168)
    at get value [as value] (app.bundle.js:1:240088)
    at Object.get [as results] (app.bundle.js:1:274513)
    at Proxy.<anonymous> (app.bundle.js:1:297479)
    at Je (app.bundle.js:1:242277)
    at Cn.fn (app.bundle.js:1:259375)
    at Cn.run (app.bundle.js:1:233168)
    at I (app.bundle.js:1:259673)
    at U (app.bundle.js:1:257927)
```

**Comment by KinesisCorporation** [comment]
Sorry about that! Working on a fix now.
